### ISSUE TITLE
외 망도우만 지원헤~~~!

### ISSUE THREAD

**Issue by dn1t** [EXON-School/Python#2]
크로스플랫폼몰라요?

**Comment by ghost** [comment]
ㅇㅈ

**Comment by sihyeokpark** [comment]
@thoratica 
제발 이런걸로 이슈 보내지좀 말아주실래요?
애초에 학교에서 맥쓰나요?
분명 저희 학교 컴퓨터 동아리에 쓸 강의자료인데?
